### ISSUE TITLE
多服务器下无法正常获取玩家在线以及无法运行命令

### ISSUE THREAD

**Issue by 577fkj** [jie65535/gc-opencommand-plugin#11]
rt

**Comment by jie65535** [comment]
你确定填写了正确的服务地址吗？

**Comment by 577fkj** [comment]
> 你确定填写了正确的服务地址吗？

是正确的

**Comment by jie65535** [comment]
多服务器是什么意思，http服务器和游戏服务器分离？如果是这样，确实可能无法调用http接口

**Comment by 577fkj** [comment]
> 多服务器是什么意思，http服务器和游戏服务器分离？如果是这样，确实可能无法调用http接口

是的 http 和游戏分离

**Comment by jie65535** [comment]
查看代码发现，如果游戏服模式设置了仅游戏，那么http服务器也不会启动，因此自然也无法接收客户端的命令请求。也许你可以尝试将游戏服改为混合模式。

**Comment by 577fkj** [comment]
> 查看代码发现，如果游戏服模式设置了仅游戏，那么http服务器也不会启动，因此自然也无法接收客户端的命令请求。也许你可以尝试将游戏服改为混合模式。

混合模式会导致白屏
