### ISSUE TITLE
关于跨域问题

### ISSUE THREAD

**Issue by mingmono** [jie65535/gc-opencommand-plugin#23]
您好，我是在浏览器直接使用jquery的post请求，但是提示跨域了，因为我不懂java，所以请问一下这个问题我应该怎么解决呢

**Comment by jie65535** [comment]
插件使用的是GC自带的HTTP服务端，我只是注册了一个接口，跨域相关问题可能得到GC那边问问。我也不是很了解java这块内容。

**Comment by mingmono** [comment]
哦哦 好的，谢谢您的回复
