### ISSUE TITLE
GcTools远程执行命令 回复无权限

### ISSUE THREAD

**Issue by caikun233** [jie65535/gc-opencommand-plugin#27]
GcTools v1.8.1，游戏服务端版本3.5（控制台显示3.4），游戏版本3.5，OpenCommand v1.5.1
GcTools界面内服务器状态都正常，远程执行插件也是正常的，验证码等步骤都正常
但生成好指令点击执行后，GcTools会报“你没有权限执行此命令。”

**Comment by jie65535** [comment]
你用相同的命令在游戏内执行呢？

**Comment by caikun233** [comment]
也是报无权限，是我服务端设置出问题了吗？上周还是正常的

**Comment by jie65535** [comment]
就是字面意思，没有权限。 在 管理->权限 里，生成一个分配所有权限的命令，然后在控制台里执行给你的账号分配权限就行了。

**Comment by caikun233** [comment]
明白了，问题已经解决，谢谢你的帮助。另外控制台告诉我标准用法是/permission [@<UID>] add <permission>，而不是/permission add [@<UID>] <permission> ，虽然能兼容就是了（）

For others:
在使用权限分配的命令时需要**关闭** 主页->生成的命令包含UID 这一选项，否则生成的命令语法不对
在管理->权限里，选择所有权限的方法是在 权限 选项栏中选择 星号（*）
