### ISSUE TITLE
[Bug Report] only returns part of the result when executing commands with very long result

### ISSUE THREAD

**Issue by fred913** [jie65535/gc-opencommand-plugin#28]
又是我。~bug体质了属于是~

## 问题复现
- 执行`help`。

## 期待表现
- 返回完整执行结果，即所有指令的使用说明

## 实际效果
- 只返回最后一条命令的使用说明。

可能是命令处理器多次回调导致的？因为在游戏中调用`help`，会显示为Server发送了很多条消息

**Comment by fred913** [comment]
此外冒昧问一句 能否加个联系方式 有些方面想求教一下

**Comment by jie65535** [comment]
感谢你反馈问题，应该可以通过CI获取最新构建，联系的话可以发到我邮箱 `jie65535@qq.com`，或者加群 `457427536` 。

**Comment by fred913** [comment]
@jie65535 了解了，但是一个星期前就申请了……
