### ISSUE TITLE
bug？服务器修改端口号后查询报错

### ISSUE THREAD

**Issue by ifrvn** [jie65535/gc-opencommand-plugin#3]
服务器端口号（server.http.bindPort）从443改为8443
用GrasscutterTools尝试查询http://[ip]:8443，报错
`查询服务端状态失败：服务器提交了协议冲突. Section=ResponseStatusLine`
![image](https://user-images.githubusercontent.com/21982381/169638068-e73d29f2-a038-4968-a61d-0f381e1e9fd8.png)

**Comment by jie65535** [comment]
也许是 `https://` ？

**Comment by nmMmnmMmn** [comment]
> 也许是 `https://` ？

试过了，无法连接到远程服务器。服务器端443端口正常开放的。把server.http.bindPort改回443倒是可以

**Comment by ifrvn** [comment]
> 也许是 `https://` ？

啊，还真是https://[ip]:8443。这怎么理解

**Comment by jie65535** [comment]
开了`ssl`，就是`https`

**Comment by ifrvn** [comment]
> 开了`ssl`，就是`https`

哦哦，是这样。感谢！
