### ISSUE TITLE
GC1.6.1版本报错does not specify an API version.

### ISSUE THREAD

**Issue by david4958606** [jie65535/gc-opencommand-plugin#33]
<WARN:PluginManager> ??Plugin opencommand-for-unstable-1.5.2.jar does not specify an API version.

使用GC最新发布的1.6.1版本

**Comment by TomyJan** [comment]
[opencommand-1.5.2.jar.rename.zip](https://github.com/jie65535/gc-opencommand-plugin/files/11636723/opencommand-1.5.2.jar.rename.zip)
