### ISSUE TITLE
未将对象引用设置到对象的实例

### ISSUE THREAD

**Issue by WenBing2078** [jie65535/gc-opencommand-plugin#34]
![屏幕截图 2023-06-04 134237](https://github.com/jie65535/gc-opencommand-plugin/assets/109894308/edd49916-d702-4d37-8b1b-4360cd316fd6)

**Comment by WenBing2078** [comment]
点击“发送验证码”之后，出现“未将对象引用设置到对象的实例”的错误

**Comment by jie65535** [comment]
这个问题在最新的插件中应该已经修复了，不过是针对GC-1.6.X的

**Comment by jie65535** [comment]
我重新发布了一个用于旧版的修复，你可以在Release中下载v1.5.3的版本试试。
