### ISSUE TITLE
新版本GCapi接口不兼容

### ISSUE THREAD

**Issue by awaae001** [jie65535/gc-opencommand-plugin#37]
服务器提示支持api-3
而插件才api-2

**Comment by jie65535** [comment]
你可以Action中下载新版本，或者用压缩文件打开插件`jar`，把配置文件 `plugin.json` 的API版本改成 `3` 就行。

**Comment by crazylei12** [comment]
> 

在哪个位置啊，plugin.json里没有相关内容啊

{
  "name": "grasscutter-plugin",
  "description": "a plugin for grasscutter-tools to connect server",
  "version": "1.0.0",
  "mainClass": "org.hff.MyPlugin",
  "authors": [
    "null"
  ]
}

**Comment by crazylei12** [comment]
> 你可以Action中下载新版本，或者用压缩文件打开插件`jar`，把配置文件 `plugin.json` 的API版本改成 `3` 就行。

在哪个位置啊，plugin.json里没有相关内容啊

{
"name": "grasscutter-plugin",
"description": "a plugin for grasscutter-tools to connect server",
"version": "1.0.0",
"mainClass": "org.hff.MyPlugin",
"authors": [
"null"
]
}
