### ISSUE TITLE
插件在更新服务端后崩溃

### ISSUE THREAD

**Issue by ZXAS007** [jie65535/gc-opencommand-plugin#6]
嗯，是这样的今天在我更新Grasscutter 版本：1.2.1-dev-c9b6290版本后服务器插件又报错崩溃了（插件122版本）
![Screenshot_2022-06-22-13-00-54-369_com.miui.gallery.jpg](https://user-images.githubusercontent.com/69531154/174947239-be214a4a-1ea2-403f-8427-3ea26852a408.jpg)

**Comment by jie65535** [comment]
他们发现更改导致大量插件不兼容，又改回来了，用之前的就可以了。我也会删除新的发布。
